### ISSUE TITLE
LSposed not work

### ISSUE THREAD

**Issue by bremaya** [Enmmmmn/magisk-on-vmos-pro#1]
For some reason the LSposed in this git doesn't load with Riru, I tried several ways and it's not loading...

**Comment by Enmmmmn** [comment]
Can I communicate in Chinese?

**Comment by bremaya** [comment]
> Can I communicate in Chinese?

👍🏽

由于某种原因，这个 git 中的 LSpose 无法加载 Riru，我尝试了几种方法，但它没有加载...

**Comment by Enmmmmn** [comment]
你使用的VMOS Pro版本是多少？
以及是否能提供/data/adb/lspd/log目录下的全部文件?

**Comment by bremaya** [comment]
重新启动 VMOS Pro 后，模块不再工作...
Riru
LSposed

**Comment by Enmmmmn** [comment]
你可以提供你使用的VMOS Pro版本吗？

**Comment by bremaya** [comment]
VMOS v3.0.1
![Screenshot_20240309-110217](https://github.com/Enmmmmn/magisk-on-vmos-pro/assets/39398165/919a542e-c5b3-4c1a-9fb4-398ee1590a09)

**Comment by Enmmmmn** [comment]
你可以正常进入虚拟机吗？
如果可以,请使用一个可以访问根目录的文件管理器访/data/adb/lspd/log并将目录内的所有的文件压缩为一个zip

**Comment by bremaya** [comment]
For some reason now the modules work correctly (so far)
[lspd_workinkg.zip](https://github.com/Enmmmmn/magisk-on-vmos-pro/files/14549901/lspd_workinkg.zip)

**Comment by Enmmmmn** [comment]
有的时候可能会出现 Riru 没有正常加载,可能重启一下虚拟机就可以正常加载了

**Comment by bremaya** [comment]
我注意到，当 Magisk 和 LSpose 未加载时，最好强制终止 VMOS 并再次启动它，它会再次工作。
