### ISSUE TITLE
如何添加其他模块？

### ISSUE THREAD

**Issue by bremaya** [Enmmmmn/magisk-on-vmos-pro#2]
除了在 Git 中修补的模块之外，我们如何向 Magisk 添加其他模块？ 您能否创建一个有关如何修补模块的教程？

**Comment by Enmmmmn** [comment]
可以直接安装适用于原版 Magisk 的模块,你也可以报告你发现无法正常运行的模块

**Comment by Enmmmmn** [comment]
你也可以尝试使用 Fix 分支,此版本兼容的模块应该更多(可能不稳定)
