### ISSUE TITLE
超级用户权限不保存

### ISSUE THREAD

**Issue by bremaya** [Enmmmmn/magisk-on-vmos-pro#3]
当使用请求超级用户权限的应用程序然后重新启动 VM 时，请求不会保存在 Magisk 中。 整个列表将被删除。

**Comment by Enmmmmn** [comment]
已知问题,原因未知

**Comment by Enmmmmn** [comment]
此问题已在2024.03.19-Canary修复

**Comment by helpcentury** [comment]
请求你的magisk支持[audiohq_module](https://github.com/Alcatraz323/audiohq_module)，这是一个能独立控制APP音量的模块，谢谢！

**Comment by Enmmmmn** [comment]
这是模块自身问题,没有适配SELinux为关闭状态,并且在将SELinux宽容后检测SELinux状态是否为宽容,否则结束安装

**Comment by Enmmmmn** [comment]
并且我在强制通过SELinux检测以安装此模块后虚拟机无法播放音频
