### ISSUE TITLE
7.1.2、64位版本，安装失败，提示Unsupported device

### ISSUE THREAD

**Issue by joyruby** [Enmmmmn/magisk-on-vmos-pro#5]
1. xposed installer 和超级用户都已经打开
2. 安装最新的版本[Magisk On VMOS Pro-2024.03.23-Canary](https://github.com/Enmmmmn/magisk-on-vmos-pro/releases/tag/2024.03.23-Canary)
3. 进入Magisk App内→点击安装→下一步→直接安装（推荐）
4. 提示: ! Unsupported device  ! Installation failed

**Comment by Enmmmmn** [comment]
请尝试使用 Fix 分支
